### ISSUE TITLE
Escaped HTML in demo

### ISSUE THREAD

**Issue by dahse89** [tranduyhung/grav-skeleton-big-picture#7]
I saw the demo of this site on getgrav.org (https://grav-theme-big-picture.flatfiledeveloper.com/) and recognized some odd output in the footer.
![Screenshot_20211103-221714_Chrome Beta](https://user-images.githubusercontent.com/5771799/140194415-1c8f5a7b-d3d7-497f-a049-faad3e86475d.jpg)

I'm not sure if it's a bug or just a misconfiguration in the demo.

I just want to let you know

**Comment by tranduyhung** [comment]
Thank you for letting us know. It was a compatibility issue with Grav 1.7. We've fixed that.
