### ISSUE TITLE
this crashes the website everytime I install it

### ISSUE THREAD

**Issue by ghost** [tranduyhung/grav-skeleton-big-picture#8]
Any thoughts as to how to go work around this?

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/99705212/153990226-a8c81832-efef-425e-aad8-85f3f130dcae.PNG)

**Comment by tranduyhung** [comment]
The latest version of this skeleton was released 2 years ago, it contains very old version of Grav and its plugins, they may not be compatible with the recent technologies (eg. PHP 8). You should build a site from scratch with the latest Grav version instead.
